# this file holds all of the prod aliases
# Application 'psufandbsites', environment 'prod'.
seosc:
  root: /var/www/html/fws/docroot
  uri: seostatecollege.com
  host: 172.104.215.47
  user: fws
ikk:
  root: /var/www/html/fws/docroot
  uri: dev.insidekellyskitchen.com
  host: 172.104.215.47
  user: fws