# this file holds all of the prod aliases
# Application 'psufandbsites', environment 'prod'.
seosc:
  root: /var/www/html/fws/docroot
  uri: seostatecollege.com
  host: 172.104.215.47
  user: fws
ikk:
  root: /var/www/html/fws/docroot
  uri: insidekellyskitchen.com
  host: 172.104.215.47
  user: fws
rv:
  root: /var/www/html/fws/docroot
  uri: rvfastfix.fisherwebsolutions.com
  host: 172.104.215.47
  user: fws
lg:
  root: /var/www/html/fws/docroot
  uri: lg.fisherwebsolutions.com
  host: 172.104.215.47
  user: fws
tuscaloosalawncare:
  root: /var/www/html/fws/docroot
  uri: tuscaloosalawncare.com
  host: 172.104.215.47
  user: fws
